/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.tenamen.musicplayer;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import tech.tenamen.musicplayer.core.PlayList;
import tech.tenamen.musicplayer.core.player.impl.*;
import tech.tenamen.musicplayer.core.searcher.SearchEngine;
import tech.tenamen.musicplayer.core.searcher.impl.*;

public class App extends Application {

    public static final String APP_NAME = "Music Player";

    private static final PlayList PLAY_LIST = new PlayList();

    public static Parent root;

    public static final SearchEngine<YouTubeProvider> YOUTUBE_ENGINE = new YouTubeSearchEngine();
    public static final SearchEngine<SoundCloudProvider> SOUNDCLOUD_ENGINE = new SoundCloudSearchEngine();

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        root = FXMLLoader.load(getClass().getResource("scene/Main.fxml"));
        final Scene scene = new Scene(root, 1315, 890);
        //scene.getStylesheets().add(this.getClass().getResource("").toExternalForm());
        primaryStage.setScene(scene);
        primaryStage.setTitle(APP_NAME);
        primaryStage.show();
    }
}
